#include "include/lib.c" 
#include "include/gc.c"
// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures
void *prev;
struct A
{
  struct A_vtable *vptr;
};
struct B
{
  struct B_vtable *vptr;
};
struct C
{
  struct C_vtable *vptr;
};
// vtables structures
struct A_vtable
{
	char *A_gc_map; 
};

struct B_vtable
{
	char *B_gc_map; 
  int (*B)(struct B * thiss);
};

struct C_vtable
{
	char *C_gc_map; 
  int (*C)(struct C * thiss);
};


//method declar
int B_B(struct B * thiss);
int C_C(struct C * thiss);
// vtables
struct A_vtable A_vtable_ = 
{
"2",
};

struct B_vtable B_vtable_ = 
{
"2",
  B_B
};

struct C_vtable C_vtable_ = 
{
"2",
  C_C
};


// methods
struct B_B_gc_frame{
	void* prev;
	char *arguments_gc_map;
	int *arguements_base_address;
	char *locals_gc_map;
	struct C * c;
	};
char *B_B_arguments_gc_map = "1";
char *B_B_locals_gc_map = "1";
int B_B(struct B * thiss)
{
	struct B_B_gc_frame frame;
	frame.prev = prev;
	prev = &frame;
	frame.arguments_gc_map = B_B_arguments_gc_map;
	frame.arguements_base_address = &thiss;
	frame.locals_gc_map = B_B_locals_gc_map;
	
  frame.c = ((struct C*)(Tiger_new (&C_vtable_, sizeof(struct C))));
prev = frame.prev;  return 10;
}
struct C_C_gc_frame{
	void* prev;
	char *arguments_gc_map;
	int *arguements_base_address;
	char *locals_gc_map;
	};
char *C_C_arguments_gc_map = "1";
char *C_C_locals_gc_map = "0";
int C_C(struct C * thiss)
{
	struct C_C_gc_frame frame;
	frame.prev = prev;
	prev = &frame;
	frame.arguments_gc_map = C_C_arguments_gc_map;
	frame.arguements_base_address = &thiss;
	frame.locals_gc_map = C_C_locals_gc_map;
	
prev = frame.prev;  return 10;
}

// main method
int Tiger_main ()
{
  struct B * x_0;
  System_out_println ((x_0=((struct B*)(Tiger_new (&B_vtable_, sizeof(struct B)))), x_0->vptr->B(x_0)));
}




int main (int argc, char **argv){
Tiger_main ();
return 0;}